name: Deploy EC2, Install Docker & Nginx, Configure Reverse Proxy

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up AWS Credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Install Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      # 4. Apply Terraform Configuration
      - name: Apply Terraform Configuration
        run: |
          terraform init
          terraform apply -auto-approve

      # 5. Display Terraform Outputs
      - name: Display Terraform Outputs
        run: |
          terraform output -json

      # 6. Install jq
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # 7. Retrieve EC2 Public IP - FIXED
      - name: Retrieve EC2 Public IP
        run: |
          echo "Retrieving EC2 Public IP..."
          
          # Get the raw output first and inspect it
          RAW_OUTPUT=$(terraform output ec2_public_ip)
          echo "Raw output: $RAW_OUTPUT"
          
          # Clean the output by removing quotes and whitespace
          EC2_PUBLIC_IP=$(echo "$RAW_OUTPUT" | tr -d '"' | tr -d ' ')
          echo "Cleaned EC2 Public IP: $EC2_PUBLIC_IP"
          
          # Validate the IP format using regex (optional but recommended)
          if [[ ! $EC2_PUBLIC_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Warning: The extracted IP doesn't match the expected format. Continuing anyway."
          fi
          
          # Set environment variable
          echo "PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
          echo "Successfully set PUBLIC_IP as an environment variable."

      # 8. Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/mykey.pem
          chmod 600 ~/.ssh/mykey.pem

      # 9. SSH into EC2 and set up Docker, pull image, and configure Nginx
      - name: SSH into EC2 and Set Up
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/mykey.pem ubuntu@${{ env.PUBLIC_IP }} << 'EOF'
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Pull and run Docker image
            sudo docker pull markhill97/simple-user-management-fastapi-app:latest
            sudo docker run -d -p 8080:80 markhill97/simple-user-management-fastapi-app:latest

            # Install and configure Nginx
            sudo apt install -y nginx
            echo "
            server {
              listen 80;
              server_name _;
              location / {
                proxy_pass http://localhost:8080;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
              }
            }
            " | sudo tee /etc/nginx/sites-available/default
            sudo systemctl restart nginx
          EOF

      # 10. Health Check
      - name: Health Check - Verify Application
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://${{ env.PUBLIC_IP }}/

      # 11. Conditional Destroy Terraform Resources
      - name: Conditional Destroy Terraform Resources
        if: ${{ success() }}
        run: |
          terraform destroy -auto-approve